from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from python_env import inject_local_site_packages, preferred_python_commands
from bworkflow_sql.subtitle_rules import split_subtitle_text
from image_index import DEFAULT_IMAGE_INDEX_PATH, resolve_image_paths
from PIL import Image, ImageDraw, ImageFont

inject_local_site_packages()

try:
    import pyJianYingDraft as draft
    from pyJianYingDraft import trange
except Exception as exc:  # pragma: no cover - environment specific
    draft = None
    trange = None
    DRAFT_IMPORT_ERROR = exc
else:
    DRAFT_IMPORT_ERROR = None

try:
    import torch
    from qwen_asr import Qwen3ForcedAligner
except Exception:  # pragma: no cover - optional dependency
    torch = None
    Qwen3ForcedAligner = None


DEFAULT_DRAFT_ROOT = r"E:\剪辑-剪映\草稿\JianyingPro Drafts"
DEFAULT_DRAFT_NAME = "自动剪辑草稿"
DEFAULT_BACKGROUND_DIR = Path(r"G:\2026项目-b站\素材-剪辑\1-背景图")
_DEFAULT_BG_CACHE: str | None = None
INTRO_AUDIO_CACHE_DIR_NAME = "_b_workflow_intro_audio"
PRICE_TITLE_CACHE_DIR_NAME = "_b_workflow_price_titles"
VOICE_CLIP_GAP_SEC = 0.0
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}
VIDEO_SUFFIXES = {".mp4", ".mov", ".mkv", ".avi"}
AUDIO_SUFFIXES = {".wav", ".mp3", ".m4a", ".aac", ".flac", ".ogg"}

def _resolve_default_background() -> str:
    global _DEFAULT_BG_CACHE
    if _DEFAULT_BG_CACHE is not None:
        return _DEFAULT_BG_CACHE
    bg_dir = DEFAULT_BACKGROUND_DIR
    if bg_dir.exists():
        images = sorted([p for p in bg_dir.iterdir() if p.is_file() and p.suffix.casefold() in IMAGE_SUFFIXES])
        if images:
            import random
            chosen = random.choice(images)
            _DEFAULT_BG_CACHE = str(chosen)
            return _DEFAULT_BG_CACHE
    return ""

DEFAULT_BACKGROUND_IMAGE = _resolve_default_background()
PUNCTUATION_TRANSLATION = str.maketrans("", "", "，。！？；：、,.!?;:()（）【】[]《》<>“”\\\"'‘’`~…—-")
WHITESPACE_RE = re.compile(r"\s+")
SYSTEM_PYTHON_COMMANDS = preferred_python_commands()
QWEN_FORCED_ALIGNER_MODEL = "Qwen/Qwen3-ForcedAligner-0.6B"
QWEN_LANGUAGE_MAP = {
    "zh": "Chinese",
    "zh-cn": "Chinese",
    "en": "English",
    "ja": "Japanese",
    "ko": "Korean",
}
QWEN_ALIGNER_CACHE: dict[str, Any] = {}


class SkillError(RuntimeError):
    pass


@dataclass
class ClipItem:
    media_path: Path | None
    audio_path: Path
    duration_sec: float
    match_name: str
    subtitle_text: str = ""
    source_type: str = "product"
    source_section: str = ""
    price_transition_title: str = ""
    display_video_path: Path | None = None
    display_video_slot: dict[str, Any] | None = None


@dataclass
class SubtitleSegment:
    start_sec: float
    duration_sec: float
    text: str


def normalize_text(value: Any) -> str:
    return str(value or "").strip()


def price_transition_title_from_entry(raw: dict[str, Any]) -> str:
    section = normalize_text(raw.get("section"))
    product_uid = normalize_text(raw.get("product_uid")).casefold()
    source_label = normalize_text(raw.get("source_label"))
    if section != "price_transition" and product_uid != "price_transition" and not source_label.startswith("价格过渡"):
        return ""

    title = normalize_text(raw.get("price_range_label"))
    if not title:
        title = source_label
        title = re.sub(r"^价格过渡\s*[:：-]?\s*", "", title).strip()
    return title


def safe_path_component(value: str, fallback: str = "draft") -> str:
    text = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "_", normalize_text(value))
    text = text.strip(" ._")
    return text or fallback


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a Jianying draft from a b-workflow manifest or matched image/audio directories."
    )
    parser.add_argument("--manifest", help="Manifest JSON generated by b-workflow or a legacy items list.")
    parser.add_argument("--draft-root", default=DEFAULT_DRAFT_ROOT, help="剪映草稿根目录。")
    parser.add_argument("--draft-name", default=DEFAULT_DRAFT_NAME, help="剪映草稿名。")
    parser.add_argument("--width", type=int, default=1920)
    parser.add_argument("--height", type=int, default=1080)
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--background-image", default=DEFAULT_BACKGROUND_IMAGE, help="背景图路径。")
    parser.add_argument("--intro-video", help="可选：前置引言成片视频。传入后会先拼接这段视频，再接商品推荐正文。")
    parser.add_argument("--image-dir", help="兼容旧测试模式：商品图片目录。")
    parser.add_argument("--audio-dir", help="兼容旧测试模式：配音目录。")
    parser.add_argument("--subtitle-language", default="zh", help="本地字幕对齐语言。")
    parser.add_argument("--subtitle-model", default="base", help="faster-whisper 模型名。")
    parser.add_argument(
        "--subtitle-engine",
        choices=["whisper", "qwen"],
        default="whisper",
        help="字幕对齐引擎。whisper 为现有方案，qwen 为强制对齐方案。",
    )
    parser.add_argument("--skip-subtitles", action="store_true", help="跳过字幕对齐。")
    parser.add_argument("--subtitle-no-vad", action="store_true", help="字幕 ASR 不启用 VAD，兼容 onnxruntime 不可用的环境。")
    parser.add_argument("--allow-replace", action="store_true", help="允许覆盖同名草稿。")
    parser.add_argument(
        "--template-draft",
        help="可选：引言模板草稿目录。传入后会复制模板并把自动生成的后半段拼接到模板后面。",
    )
    parser.add_argument("--image-category", help="可选：图片分类，用于在 manifest 缺图时回查图片索引。")
    parser.add_argument("--image-user", help="可选：图片用户，用于在 manifest 缺图时回查图片索引。")
    parser.add_argument("--image-set", help="可选：图片模板，用于在 manifest 缺图时回查图片索引。")
    parser.add_argument("--image-index-path", help="可选：图片索引 JSON 路径。")
    return parser.parse_args()


def ensure_runtime_dependencies() -> None:
    if draft is not None and trange is not None:
        return
    raise SkillError(f"pyJianYingDraft 不可用，无法生成剪映草稿：{DRAFT_IMPORT_ERROR}")


def load_manifest_payload(path: Path) -> tuple[list[dict[str, Any]], str]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if isinstance(payload, list):
        return payload, "legacy_items"
    if isinstance(payload, dict):
        if isinstance(payload.get("items"), list):
            return payload["items"], "legacy_items"
        if isinstance(payload.get("entries"), list):
            entries = sorted(
                [entry for entry in payload["entries"] if isinstance(entry, dict)],
                key=lambda entry: int(entry.get("order_index") or 0),
            )
            return entries, "b_workflow_entries"
    raise SkillError("Manifest 必须是列表，或包含 `items` / `entries` 的对象。")


def fallback_manifest_media_paths(
    payload: Any,
    *,
    image_category: str,
    image_user: str,
    image_set: str,
    image_index_path: Path,
) -> dict[str, Any]:
    if not isinstance(payload, dict):
        return {
            "image_category": image_category,
            "image_user": image_user,
            "image_set": image_set,
            "resolved_count": 0,
            "missing_uids": [],
        }

    entries = payload.get("entries")
    if not isinstance(entries, list):
        return {
            "image_category": image_category,
            "image_user": image_user,
            "image_set": image_set,
            "resolved_count": 0,
            "missing_uids": [],
        }

    effective_category = normalize_text(image_category or payload.get("image_category"))
    effective_user = normalize_text(image_user or payload.get("image_user"))
    effective_set = normalize_text(image_set or payload.get("image_set"))
    if not all((effective_category, effective_user, effective_set)):
        return {
            "image_category": effective_category,
            "image_user": effective_user,
            "image_set": effective_set,
            "resolved_count": 0,
            "missing_uids": [],
        }

    needs_fallback: list[str] = []
    seen_uids: set[str] = set()
    for raw in entries:
        if not isinstance(raw, dict):
            continue
        if normalize_text(raw.get("type")) != "product":
            continue
        if normalize_text(raw.get("image_path")) or normalize_text(raw.get("video_path")):
            continue
        uid = normalize_text(raw.get("product_uid"))
        if uid and uid not in seen_uids:
            needs_fallback.append(uid)
            seen_uids.add(uid)

    if not needs_fallback:
        return {
            "image_category": effective_category,
            "image_user": effective_user,
            "image_set": effective_set,
            "resolved_count": 0,
            "missing_uids": [],
        }

    indexed_image_paths, missing_uids = resolve_image_paths(
        index_path=image_index_path,
        category=effective_category,
        image_user=effective_user,
        image_set=effective_set,
        product_uids=needs_fallback,
    )

    resolved_count = 0
    for raw in entries:
        if not isinstance(raw, dict):
            continue
        if normalize_text(raw.get("type")) != "product":
            continue
        if normalize_text(raw.get("image_path")) or normalize_text(raw.get("video_path")):
            continue
        uid = normalize_text(raw.get("product_uid"))
        resolved_path = indexed_image_paths.get(uid, "")
        if resolved_path:
            raw["image_path"] = resolved_path
            resolved_count += 1

    payload["image_category"] = effective_category
    payload["image_user"] = effective_user
    payload["image_set"] = effective_set
    payload["image_index_path"] = str(image_index_path)
    return {
        "image_category": effective_category,
        "image_user": effective_user,
        "image_set": effective_set,
        "resolved_count": resolved_count,
        "missing_uids": missing_uids,
    }


def probe_audio_duration(audio_path: Path) -> float:
    try:
        return draft.AudioMaterial(str(audio_path)).duration / 1_000_000
    except Exception:
        pass

    command = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "json",
        str(audio_path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="ignore", check=True)
    payload = json.loads(result.stdout)
    duration_text = payload.get("format", {}).get("duration")
    if not duration_text:
        raise SkillError(f"无法读取音频时长：{audio_path}")
    duration = float(duration_text)
    if duration <= 0:
        raise SkillError(f"音频时长必须大于 0：{audio_path}")
    return duration


def probe_media_duration(media_path: Path) -> float:
    if draft is not None:
        try:
            return draft.VideoMaterial(str(media_path)).duration / 1_000_000
        except Exception:
            pass

    command = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "json",
        str(media_path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="ignore", check=True)
    payload = json.loads(result.stdout)
    duration_text = payload.get("format", {}).get("duration")
    if not duration_text:
        raise SkillError(f"无法读取媒体时长：{media_path}")
    duration = float(duration_text)
    if duration <= 0:
        raise SkillError(f"媒体时长必须大于 0：{media_path}")
    return duration


def probe_video_size(media_path: Path) -> tuple[int, int]:
    command = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        str(media_path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="ignore", check=True)
    payload = json.loads(result.stdout)
    streams = payload.get("streams")
    if not isinstance(streams, list) or not streams:
        raise SkillError(f"无法读取视频尺寸：{media_path}")
    stream = streams[0]
    width = int(stream.get("width") or 0)
    height = int(stream.get("height") or 0)
    if width <= 0 or height <= 0:
        raise SkillError(f"视频尺寸必须大于 0：{media_path}")
    return width, height


def extract_audio_from_video(video_path: Path, output_path: Path) -> Path:
    command = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),
        "-vn",
        "-ac",
        "2",
        "-ar",
        "44100",
        "-c:a",
        "pcm_s16le",
        str(output_path),
    ]
    subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="ignore", check=True)
    if not output_path.exists():
        raise SkillError(f"引言视频音频抽取失败：{video_path}")
    return output_path


def build_intro_clip_item(intro_video_path: Path, temp_dir: Path) -> ClipItem:
    if not intro_video_path.exists():
        raise FileNotFoundError(f"前置引言视频不存在：{intro_video_path}")
    if intro_video_path.suffix.lower() not in VIDEO_SUFFIXES:
        raise SkillError(f"前置引言视频格式不支持：{intro_video_path.suffix} ({intro_video_path})")

    raw_duration_sec = probe_media_duration(intro_video_path)
    duration_sec = max(raw_duration_sec - 0.02, 0.1)
    return ClipItem(
        media_path=intro_video_path,
        audio_path=intro_video_path,
        duration_sec=duration_sec,
        match_name=intro_video_path.stem,
        subtitle_text="",
        source_type="intro_video",
    )


def resolve_media_path(path_text: str, base_dir: Path) -> Path:
    path = Path(path_text)
    return (base_dir / path).resolve() if not path.is_absolute() else path.resolve()


def choose_entry_media(raw: dict[str, Any], base_dir: Path) -> Path | None:
    image_path = normalize_text(raw.get("image_path"))
    if not image_path:
        return None
    return resolve_media_path(image_path, base_dir)


def build_items_from_manifest(
    manifest_path: Path,
    *,
    image_category: str = "",
    image_user: str = "",
    image_set: str = "",
    image_index_path: Path | None = None,
) -> tuple[list[ClipItem], dict[str, Any]]:
    payload = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    fallback_summary = {
        "image_category": normalize_text(image_category),
        "image_user": normalize_text(image_user),
        "image_set": normalize_text(image_set),
        "resolved_count": 0,
        "missing_uids": [],
    }
    if image_index_path is None:
        image_index_path = DEFAULT_IMAGE_INDEX_PATH.resolve()
    if isinstance(payload, dict):
        fallback_summary = fallback_manifest_media_paths(
            payload,
            image_category=image_category,
            image_user=image_user,
            image_set=image_set,
            image_index_path=image_index_path,
        )

    raw_items, manifest_mode = load_manifest_payload(manifest_path)
    if isinstance(payload, dict):
        entries = payload.get("entries")
        if isinstance(entries, list) and manifest_mode == "b_workflow_entries":
            raw_items = entries
    items: list[ClipItem] = []
    skipped_entries: list[dict[str, Any]] = []
    skipped_display_videos: list[dict[str, Any]] = []
    base_dir = manifest_path.parent

    for index, raw in enumerate(raw_items, start=1):
        if manifest_mode == "legacy_items":
            media_path = resolve_media_path(raw["image_path"], base_dir)
            audio_path = resolve_media_path(raw["audio_path"], base_dir)
            subtitle_text = normalize_text(raw.get("text"))
            source_type = "legacy_item"
            source_section = ""
            price_transition_title = ""
            display_video_path = None
            display_video_slot = None
        else:
            entry_type = normalize_text(raw.get("type")) or "unknown"
            source_section = normalize_text(raw.get("section"))
            price_transition_title = price_transition_title_from_entry(raw)
            audio_text = normalize_text(raw.get("audio_path"))
            media_path = choose_entry_media(raw, base_dir)
            display_video_text = normalize_text(raw.get("display_video_path"))
            display_video_path = resolve_media_path(display_video_text, base_dir) if display_video_text else None
            display_video_slot = raw.get("display_video_slot") if isinstance(raw.get("display_video_slot"), dict) else None
            if not audio_text:
                skipped_entries.append(
                    {
                        "index": index,
                        "type": entry_type,
                        "reason": "缺少音频路径",
                    }
                )
                continue
            if media_path is None and display_video_path is None and entry_type not in {"transition", "closing"}:
                skipped_entries.append(
                    {
                        "index": index,
                        "type": entry_type,
                        "reason": "缺少可用媒体路径",
                    }
                )
                continue
            audio_path = resolve_media_path(audio_text, base_dir)
            subtitle_text = normalize_text(raw.get("text"))
            source_type = entry_type

        if media_path is not None and not media_path.exists():
            raise FileNotFoundError(f"条目 {index} 的媒体文件不存在：{media_path}")
        if media_path is not None and media_path.suffix.lower() not in IMAGE_SUFFIXES and media_path.suffix.lower() not in VIDEO_SUFFIXES:
            raise SkillError(f"暂不支持的媒体类型：{media_path.suffix} ({media_path})")
        if display_video_path is not None and (
            not display_video_path.exists() or display_video_path.suffix.lower() not in VIDEO_SUFFIXES
        ):
            reason = "文件不存在" if not display_video_path.exists() else f"不支持的格式：{display_video_path.suffix}"
            skipped_display_videos.append(
                {
                    "index": index,
                    "product_uid": normalize_text(raw.get("product_uid")),
                    "product_name": normalize_text(raw.get("product_name")),
                    "path": str(display_video_path),
                    "reason": reason,
                }
            )
            display_video_path = None
            display_video_slot = None
        if not audio_path.exists():
            raise FileNotFoundError(f"条目 {index} 的音频文件不存在：{audio_path}")
        if audio_path.suffix.lower() not in AUDIO_SUFFIXES:
            raise SkillError(f"暂不支持的音频类型：{audio_path.suffix} ({audio_path})")

        items.append(
            ClipItem(
                media_path=media_path,
                audio_path=audio_path,
                duration_sec=probe_audio_duration(audio_path),
                match_name=audio_path.stem,
                subtitle_text=subtitle_text,
                source_type=source_type,
                source_section=source_section,
                price_transition_title=price_transition_title,
                display_video_path=display_video_path,
                display_video_slot=display_video_slot,
            )
        )

    if not items:
        raise SkillError("Manifest 里没有可生成草稿的条目。")

    return items, {
        "match_mode": manifest_mode,
        "matched_items": len(items),
        "skipped_entries": skipped_entries,
        "skipped_display_videos": skipped_display_videos,
        "image_fallback": fallback_summary,
    }


def list_media_files(directory: Path, suffixes: set[str]) -> list[Path]:
    if not directory.exists():
        raise FileNotFoundError(f"目录不存在：{directory}")
    if not directory.is_dir():
        raise NotADirectoryError(f"期望目录，但拿到的是文件：{directory}")
    files = [path for path in directory.iterdir() if path.is_file() and path.suffix.lower() in suffixes]
    if not files:
        raise SkillError(f"目录里没有可用素材：{directory}")
    return sorted(files, key=lambda path: path.name.lower())


def pick_best_image_match(audio_stem: str, image_stems: dict[str, Path]) -> Path | None:
    if audio_stem in image_stems:
        return image_stems[audio_stem]
    candidates = [stem for stem in image_stems if audio_stem.startswith(stem) or stem.startswith(audio_stem)]
    if not candidates:
        return None
    return image_stems[max(candidates, key=len)]


def build_items_from_directories(image_dir: Path, audio_dir: Path) -> tuple[list[ClipItem], dict[str, Any]]:
    image_files = list_media_files(image_dir, IMAGE_SUFFIXES)
    audio_files = list_media_files(audio_dir, AUDIO_SUFFIXES)

    image_stems: dict[str, Path] = {}
    duplicates: set[str] = set()
    for image_path in image_files:
        if image_path.stem in image_stems:
            duplicates.add(image_path.stem)
        image_stems[image_path.stem] = image_path
    if duplicates:
        names = ", ".join(sorted(duplicates))
        raise SkillError(f"图片文件名去扩展后有重名，无法可靠匹配：{names}")

    items: list[ClipItem] = []
    matched_images: set[Path] = set()
    unmatched_audio: list[str] = []
    for audio_path in audio_files:
        image_path = pick_best_image_match(audio_path.stem, image_stems)
        if image_path is None:
            unmatched_audio.append(audio_path.name)
            continue
        matched_images.add(image_path)
        items.append(
            ClipItem(
                media_path=image_path.resolve(),
                audio_path=audio_path.resolve(),
                duration_sec=probe_audio_duration(audio_path),
                match_name=audio_path.stem,
                subtitle_text="",
                source_type="directory_match",
            )
        )
    if not items:
        raise SkillError("没有匹配成功的图片和音频。")
    unused_images = [path.name for path in image_files if path not in matched_images]
    return items, {
        "match_mode": "directory",
        "matched_items": len(items),
        "unmatched_audio": unmatched_audio,
        "unused_images": unused_images,
        "skipped_entries": [],
    }


def sec_text(value: float) -> str:
    return f"{value:.6f}s"


def normalize_subtitle_text(text: str) -> str:
    text = WHITESPACE_RE.sub("", text)
    return text.translate(PUNCTUATION_TRANSLATION)


def split_transcript_clauses(text: str) -> list[str]:
    return split_subtitle_text(text)


def split_longest_clause(clauses: list[str]) -> list[str]:
    if not clauses:
        return clauses
    index = max(range(len(clauses)), key=lambda i: len(clauses[i]))
    clause = clauses[index]
    if len(clause) <= 1:
        return clauses
    midpoint = max(1, len(clause) // 2)
    clauses[index:index + 1] = [clause[:midpoint], clause[midpoint:]]
    return clauses


def subtitle_python_commands() -> list[list[str]]:
    commands: list[list[str]] = []
    override = normalize_text(os.environ.get("BWORKFLOW_JIANYING_SUBTITLE_PYTHON"))
    if override:
        commands.append([override])
    local_asr_python = Path(__file__).resolve().parents[2] / ".venv-asr" / "Scripts" / "python.exe"
    if local_asr_python.exists():
        commands.append([str(local_asr_python)])
    for command in SYSTEM_PYTHON_COMMANDS:
        if command not in commands:
            commands.append(command)
    return commands


def run_alignment_asr(audio_path: Path, model_name: str, language: str, *, vad_filter: bool = True) -> list[dict[str, Any]]:
    code = """
import json
import sys
from faster_whisper import WhisperModel

audio_path = sys.argv[1]
model_name = sys.argv[2]
language = sys.argv[3]
vad_filter = sys.argv[4] == "1"

model = WhisperModel(model_name, device="cpu", compute_type="int8")
segments, _info = model.transcribe(
    audio_path,
    language=language,
    vad_filter=vad_filter,
    word_timestamps=True,
    beam_size=5,
)

payload = []
for seg in segments:
    payload.append(
        {
            "start": round(seg.start, 3),
            "end": round(seg.end, 3),
            "text": seg.text.strip(),
        }
    )

print(json.dumps(payload, ensure_ascii=False))
""".strip()

    with tempfile.TemporaryDirectory(prefix="jy_subtitle_") as temp_dir:
        temp_audio = Path(temp_dir) / f"audio{audio_path.suffix.lower()}"
        shutil.copy2(audio_path, temp_audio)
        last_error: RuntimeError | None = None
        for command in subtitle_python_commands():
            try:
                result = subprocess.run(
                    [*command, "-c", code, str(temp_audio), model_name, language, "1" if vad_filter else "0"],
                    capture_output=True,
                    text=True,
                    check=True,
                )
                return json.loads(result.stdout)
            except (subprocess.CalledProcessError, json.JSONDecodeError) as exc:
                last_error = RuntimeError(
                    f"字幕对齐失败（{' '.join(command)}）：{exc}\n{getattr(exc, 'stderr', '')}"
                )
        raise last_error or RuntimeError("没有可用的 Python 运行时来执行字幕对齐。")


def partition_clauses_to_segments(clauses: list[str], segment_weights: list[float]) -> list[str]:
    if not clauses or not segment_weights:
        return []

    while len(clauses) < len(segment_weights):
        previous = list(clauses)
        clauses = split_longest_clause(clauses)
        if clauses == previous:
            break

    if len(clauses) <= len(segment_weights):
        return clauses + [""] * (len(segment_weights) - len(clauses))

    clause_lengths = [max(len(clause), 1) for clause in clauses]
    total_clause_length = sum(clause_lengths)
    weight_sum = sum(segment_weights) or float(len(segment_weights))
    targets = [weight / weight_sum * total_clause_length for weight in segment_weights]

    prefix = [0]
    for length in clause_lengths:
        prefix.append(prefix[-1] + length)

    segment_count = len(segment_weights)
    clause_count = len(clauses)
    dp = [[math.inf] * (clause_count + 1) for _ in range(segment_count + 1)]
    prev = [[-1] * (clause_count + 1) for _ in range(segment_count + 1)]
    dp[0][0] = 0.0

    for segment_index in range(1, segment_count + 1):
        min_clause_index = segment_index
        max_clause_index = clause_count - (segment_count - segment_index)
        for clause_index in range(min_clause_index, max_clause_index + 1):
            for start_index in range(segment_index - 1, clause_index):
                group_length = prefix[clause_index] - prefix[start_index]
                cost = (group_length - targets[segment_index - 1]) ** 2
                candidate = dp[segment_index - 1][start_index] + cost
                if candidate < dp[segment_index][clause_index]:
                    dp[segment_index][clause_index] = candidate
                    prev[segment_index][clause_index] = start_index

    groups: list[str] = []
    clause_index = clause_count
    for segment_index in range(segment_count, 0, -1):
        start_index = prev[segment_index][clause_index]
        if start_index < 0:
            start_index = max(0, clause_index - 1)
        groups.append("".join(clauses[start_index:clause_index]))
        clause_index = start_index
    groups.reverse()
    return groups


def build_subtitle_segments(
    audio_path: Path,
    transcript_text: str,
    offset_sec: float,
    model_name: str,
    language: str,
    engine: str = "whisper",
    *,
    vad_filter: bool = True,
) -> list[SubtitleSegment]:
    clauses = split_transcript_clauses(transcript_text)
    if not clauses:
        return []
    if engine == "qwen":
        return build_qwen_subtitle_segments(audio_path, clauses, offset_sec, language)

    asr_segments = run_alignment_asr(audio_path, model_name, language, vad_filter=vad_filter)
    if not asr_segments:
        return []

    weights = [
        max(len(normalize_subtitle_text(segment.get("text", ""))), segment["end"] - segment["start"], 1.0)
        for segment in asr_segments
    ]
    texts = partition_clauses_to_segments(clauses, weights)

    results: list[SubtitleSegment] = []
    for segment, text in zip(asr_segments, texts):
        display_text = text.strip()
        if not normalize_subtitle_text(display_text):
            continue
        results.append(
            SubtitleSegment(
                start_sec=offset_sec + float(segment["start"]),
                duration_sec=max(float(segment["end"]) - float(segment["start"]), 0.1),
                text=display_text,
            )
        )
    return results


def get_qwen_forced_aligner() -> Any:
    if QWEN_FORCED_ALIGNER_MODEL in QWEN_ALIGNER_CACHE:
        return QWEN_ALIGNER_CACHE[QWEN_FORCED_ALIGNER_MODEL]
    if Qwen3ForcedAligner is None or torch is None:
        raise SkillError("当前环境未安装 qwen-asr 或 torch，无法使用 Qwen 强制对齐。")

    model_kwargs: dict[str, Any] = {}
    if torch.cuda.is_available():
        model_kwargs["device_map"] = "cuda:0"
        model_kwargs["dtype"] = torch.bfloat16
    else:
        model_kwargs["device_map"] = "cpu"
    aligner = Qwen3ForcedAligner.from_pretrained(QWEN_FORCED_ALIGNER_MODEL, **model_kwargs)
    QWEN_ALIGNER_CACHE[QWEN_FORCED_ALIGNER_MODEL] = aligner
    return aligner


def build_qwen_subtitle_segments(
    audio_path: Path,
    clauses: list[str],
    offset_sec: float,
    language: str,
) -> list[SubtitleSegment]:
    aligner = get_qwen_forced_aligner()
    qwen_language = QWEN_LANGUAGE_MAP.get(language.lower(), language)
    results = aligner.align(audio=str(audio_path), text="".join(clauses), language=qwen_language)
    items = results[0].items if isinstance(results, list) else results.items

    clause_segments: list[SubtitleSegment] = []
    item_index = 0
    for clause in clauses:
        target = clause
        built = ""
        start_time: float | None = None
        end_time: float | None = None
        while item_index < len(items) and len(built) < len(target):
            token_text = normalize_subtitle_text(getattr(items[item_index], "text", ""))
            if token_text:
                if start_time is None:
                    start_time = float(getattr(items[item_index], "start_time", 0.0))
                end_time = float(getattr(items[item_index], "end_time", 0.0))
                built += token_text
            item_index += 1

        if not built or start_time is None or end_time is None:
            continue
        clause_segments.append(
            SubtitleSegment(
                start_sec=offset_sec + start_time,
                duration_sec=max(end_time - start_time, 0.1),
                text=target,
            )
        )
    return clause_segments


def load_price_title_font(size: int) -> Any:
    font_candidates = [
        Path(r"C:\Windows\Fonts\msyhbd.ttc"),
        Path(r"C:\Windows\Fonts\msyh.ttc"),
        Path(r"C:\Windows\Fonts\simhei.ttf"),
        Path(r"C:\Windows\Fonts\simsun.ttc"),
    ]
    for font_path in font_candidates:
        if font_path.exists():
            return ImageFont.truetype(str(font_path), size)
    return ImageFont.load_default()


def build_price_transition_title_image(
    title: str,
    output_dir: Path,
    canvas_width: int,
    canvas_height: int,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    title_hash = hashlib.sha1(title.encode("utf-8")).hexdigest()[:10]
    output_path = output_dir / f"{safe_path_component(title, 'price-title')}-{title_hash}.png"
    if output_path.exists():
        return output_path

    image = Image.new("RGBA", (canvas_width, canvas_height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    font_size = max(96, min(170, int(canvas_height * 0.14)))
    max_width = canvas_width * 0.82
    while font_size > 72:
        font = load_price_title_font(font_size)
        bbox = draw.textbbox((0, 0), title, font=font)
        if bbox[2] - bbox[0] <= max_width:
            break
        font_size -= 6

    x = canvas_width / 2
    y = canvas_height / 2
    for offset, alpha in ((8, 95), (4, 130)):
        draw.text((x + offset, y + offset), title, font=font, anchor="mm", fill=(0, 0, 0, alpha))
    draw.text((x, y), title, font=font, anchor="mm", fill=(255, 255, 255, 255))
    image.save(output_path)
    return output_path


def build_price_transition_title_segment(
    title: str,
    start_sec: float,
    duration_sec: float,
    title_image_dir: Path,
    canvas_width: int,
    canvas_height: int,
) -> Any:
    image_path = build_price_transition_title_image(title, title_image_dir, canvas_width, canvas_height)
    segment = draft.VideoSegment(
        str(image_path),
        trange(sec_text(start_sec), sec_text(duration_sec)),
    )
    intro_animation = getattr(draft.IntroType, "向上滑动", None)
    outro_animation = getattr(draft.OutroType, "渐隐", None)
    if intro_animation is not None:
        segment.add_animation(intro_animation, sec_text(min(0.45, max(duration_sec * 0.25, 0.1))))
    if outro_animation is not None and duration_sec > 0.4:
        segment.add_animation(outro_animation, sec_text(min(0.35, max(duration_sec * 0.2, 0.1))))
    return segment


def build_media_clip_settings(media_path: Path, canvas_width: int, canvas_height: int) -> Any | None:
    if media_path.suffix.lower() not in IMAGE_SUFFIXES:
        return None

    try:
        with Image.open(media_path) as image:
            source_width, source_height = image.size
    except Exception:
        return None

    if source_width <= 0 or source_height <= 0 or canvas_width <= 0 or canvas_height <= 0:
        return None

    fit_scale = min(canvas_width / source_width, canvas_height / source_height)
    display_height = source_height * fit_scale
    vertical_blank = max(canvas_height - display_height, 0.0)
    if vertical_blank <= 1.0:
        return None

    transform_y = vertical_blank / canvas_height
    return draft.ClipSettings(transform_y=transform_y)


def build_display_video_clip_settings(
    display_video_path: Path,
    slot: dict[str, Any],
    canvas_width: int,
    canvas_height: int,
) -> Any:
    source_width, source_height = probe_video_size(display_video_path)
    if source_width <=0 or source_height <=0:
        return draft.ClipSettings()
    slot_x = float(slot.get('x') or 0)
    slot_y = float(slot.get('y') or 0)
    slot_width = float(slot.get('width') or 0)
    slot_height = float(slot.get('height') or 0)
    if slot_width <=0 or slot_height <=0 or canvas_width <=0 or canvas_height <=0:
        return draft.ClipSettings()

    #剪映 clip_settings.scale 是相对 source size 的缩放系数，
    # clip_settings.transform 是相对画布中心的位移（单位：半画布宽/高）。
    #视频实际渲染尺寸 = source * scale，video中心 = canvas_center + transform * canvas/2。
    center_x = slot_x + slot_width /2
    center_y = slot_y + slot_height /2
    transform_x = (center_x - canvas_width /2) / (canvas_width /2)
    # pyJianYingDraft/剪映的 Y 轴位移和常规屏幕坐标方向相反，向下需要负值。
    transform_y = -((center_y - canvas_height /2) / (canvas_height /2))

    if normalize_text(slot.get('coordinate_mode')) == 'clip_transform_pixels':
        # clip_transform_pixels模式：视频直接贴到 slot矩形（允许变形），渲染尺寸 = slot尺寸。
        scale_x = slot_width / source_width
        scale_y = slot_height / source_height
        return draft.ClipSettings(
            scale_x=scale_x,
            scale_y=scale_y,
            transform_x=transform_x,
            transform_y=transform_y,
        )

    # 默认模式：保持视频宽高比，让视频填满 slot 长边，video中心 = slot中心（letterbox/pillarbox）。
    source_aspect = source_width / source_height
    slot_aspect = slot_width / slot_height
    if source_aspect >= slot_aspect:
        scale = slot_width / source_width
    else:
        scale = slot_height / source_height
    override_scale = slot.get('display_scale')
    if override_scale is not None:
        try:
            scale = float(override_scale)
        except (TypeError, ValueError):
            pass
    return draft.ClipSettings(
        scale_x=scale,
        scale_y=scale,
        transform_x=transform_x,
        transform_y=transform_y,
    )

def update_draft_meta(
 draft_dir: Path,
    draft_name: str,
    total_duration_sec: float,
    *,
    fallback_payload: dict[str, Any] | None = None,
) -> None:
    meta_path = draft_dir / "draft_meta_info.json"
    content_path = primary_draft_content_path(draft_dir)
    content_payload = read_json_object(content_path) if content_path is not None else {}
    generated_materials = build_meta_draft_materials(content_payload)
    payload: dict[str, Any]
    if meta_path.exists():
        try:
            loaded = json.loads(meta_path.read_text(encoding="utf-8"))
            payload = loaded if isinstance(loaded, dict) else {}
        except (json.JSONDecodeError, OSError, UnicodeDecodeError):
            payload = copy.deepcopy(fallback_payload) if isinstance(fallback_payload, dict) else {}
    else:
            payload = copy.deepcopy(fallback_payload) if isinstance(fallback_payload, dict) else {}
    fallback_payload = fallback_payload if isinstance(fallback_payload, dict) else {}
    fallback_materials = fallback_payload.get("draft_materials")
    if generated_materials_has_values(generated_materials):
        payload["draft_materials"] = generated_materials
    elif not isinstance(payload.get("draft_materials"), list) or not payload.get("draft_materials"):
        if isinstance(fallback_materials, list) and fallback_materials:
            payload["draft_materials"] = copy.deepcopy(fallback_materials)
        else:
            payload["draft_materials"] = [
                {"type": 0, "value": []},
                {"type": 1, "value": []},
                {"type": 2, "value": []},
                {"type": 3, "value": []},
                {"type": 6, "value": []},
                {"type": 7, "value": []},
                {"type": 8, "value": []},
            ]
    fallback_size = int(fallback_payload.get("draft_timeline_materials_size_") or 0)
    if int(payload.get("draft_timeline_materials_size_") or 0) <= 0:
        content_size = content_path.stat().st_size if content_path is not None and content_path.exists() else 0
        payload["draft_timeline_materials_size_"] = max(content_size, fallback_size, 3432)
    now_us = int(time.time() * 1_000_000)
    payload.setdefault("tm_draft_create", now_us)
    payload["tm_draft_modified"] = now_us
    payload["draft_name"] = draft_name
    payload["draft_root_path"] = str(draft_dir.parent)
    payload["draft_fold_path"] = str(draft_dir)
    payload["draft_id"] = uuid.uuid4().hex
    payload["tm_duration"] = int(round(total_duration_sec * 1_000_000))
    meta_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def primary_draft_content_path(draft_dir: Path) -> Path | None:
    for candidate in (
        draft_dir / "draft_content.json",
        draft_dir / "template-2.tmp",
        draft_dir / "template.tmp",
    ):
        if candidate.exists() and candidate.stat().st_size > 0:
            return candidate
    timeline_root = draft_dir / "Timelines"
    if timeline_root.exists():
        for candidate in timeline_root.rglob("draft_content.json"):
            if candidate.exists() and candidate.stat().st_size > 0:
                return candidate
    return None


def draft_content_paths(draft_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for candidate in (
        draft_dir / "draft_content.json",
        draft_dir / "draft_content.json.bak",
        draft_dir / "template-2.tmp",
        draft_dir / "template.tmp",
    ):
        if candidate.exists() and candidate.stat().st_size > 0:
            paths.append(candidate)
    timeline_root = draft_dir / "Timelines"
    if timeline_root.exists():
        paths.extend(
            candidate
            for candidate in timeline_root.rglob("draft_content.json")
            if candidate.exists() and candidate.stat().st_size > 0
        )
    seen: set[Path] = set()
    unique: list[Path] = []
    for path in paths:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(path)
    return unique


def normalize_content_media_materials(payload: dict[str, Any]) -> bool:
    changed = False
    materials = payload.get("materials")
    if not isinstance(materials, dict):
        return False
    videos = materials.get("videos")
    if not isinstance(videos, list):
        return False
    for material in videos:
        if not isinstance(material, dict):
            continue
        material_id = normalize_text(material.get("id") or material.get("material_id"))
        if not material_id:
            continue
        if not normalize_text(material.get("local_material_id")):
            material["local_material_id"] = material_id
            changed = True
        if not normalize_text(material.get("material_id")):
            material["material_id"] = material_id
            changed = True
    return changed


def patch_draft_content_media_metadata(draft_dir: Path) -> None:
    for content_path in draft_content_paths(draft_dir):
        payload = read_json_object(content_path)
        if not payload:
            continue
        if normalize_content_media_materials(payload):
            write_json_object(content_path, payload)


def generated_materials_has_values(draft_materials: list[dict[str, Any]]) -> bool:
    return any(bool(item.get("value")) for item in draft_materials if isinstance(item, dict))


def empty_meta_draft_materials() -> list[dict[str, Any]]:
    return [
        {"type": 0, "value": []},
        {"type": 1, "value": []},
        {"type": 2, "value": []},
        {"type": 3, "value": []},
        {"type": 6, "value": []},
        {"type": 7, "value": []},
        {"type": 8, "value": []},
    ]


def media_meta_entry(material: dict[str, Any], *, outer_type: int, metetype: str, now_us: int) -> dict[str, Any] | None:
    path_text = normalize_text(material.get("path"))
    if not path_text:
        return None
    path = Path(path_text)
    if not path.exists():
        return None
    try:
        stat = path.stat()
    except OSError:
        return None
    name = normalize_text(material.get("material_name") or material.get("name") or path.name)
    item_id = normalize_text(material.get("local_material_id") or material.get("id") or material.get("material_id"))
    return {
        "create_time": int(stat.st_ctime),
        "duration": int(material.get("duration") or 0),
        "extra_info": name,
        "file_Path": path_text,
        "height": int(material.get("height") or 0),
        "id": item_id or uuid.uuid4().hex,
        "import_time": int(now_us / 1_000_000),
        "import_time_ms": now_us,
        "item_source": 1,
        "md5": "",
        "metetype": metetype,
        "roughcut_time_range": {"duration": -1, "start": -1},
        "sub_time_range": {"duration": -1, "start": -1},
        "type": outer_type,
        "width": int(material.get("width") or 0),
    }


def build_meta_draft_materials(content_payload: dict[str, Any]) -> list[dict[str, Any]]:
    draft_materials = empty_meta_draft_materials()
    by_type = {int(item["type"]): item["value"] for item in draft_materials}
    materials = content_payload.get("materials")
    if not isinstance(materials, dict):
        return draft_materials
    now_us = int(time.time() * 1_000_000)
    seen_paths: set[tuple[int, str]] = set()

    videos = materials.get("videos")
    if isinstance(videos, list):
        for material in videos:
            if not isinstance(material, dict):
                continue
            metetype = normalize_text(material.get("type")) or "video"
            entry = media_meta_entry(material, outer_type=0, metetype=metetype, now_us=now_us)
            if entry is None:
                continue
            key = (0, entry["file_Path"].casefold())
            if key in seen_paths:
                continue
            seen_paths.add(key)
            by_type[0].append(entry)

    audios = materials.get("audios")
    if isinstance(audios, list):
        for material in audios:
            if not isinstance(material, dict):
                continue
            entry = media_meta_entry(material, outer_type=8, metetype="none", now_us=now_us)
            if entry is None:
                continue
            key = (8, entry["file_Path"].casefold())
            if key in seen_paths:
                continue
            seen_paths.add(key)
            by_type[8].append(entry)
    return draft_materials


def read_json_object(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def write_json_object(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def build_default_draft_name(manifest_path: Path) -> str:
    name = manifest_path.name
    if name.endswith(".manifest.json"):
        return name[:-len(".manifest.json")]
    return manifest_path.stem


def load_template_draft(template_dir: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    if not template_dir.exists():
        raise FileNotFoundError(f"模板草稿不存在：{template_dir}")
    if not template_dir.is_dir():
        raise NotADirectoryError(f"模板草稿必须是目录：{template_dir}")

    draft_content_path = template_dir / "draft_content.json"
    draft_meta_path = template_dir / "draft_meta_info.json"
    subdraft_content_path = template_dir / "subdraft" / "draft_content.json"

    content: dict[str, Any] | None = None
    content_error = ""
    for candidate_path, source_label in (
        (draft_content_path, "draft_content.json"),
        (subdraft_content_path, "subdraft/draft_content.json"),
    ):
        if not candidate_path.exists():
            continue
        try:
            loaded = json.loads(candidate_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError, UnicodeDecodeError) as exc:
            content_error = f"{source_label} 不可解析：{exc}"
            continue
        if isinstance(loaded, dict):
            content = loaded
            break
        content_error = f"{source_label} 结构异常，必须是对象"

    if content is None:
        if not draft_content_path.exists() and not subdraft_content_path.exists():
            raise SkillError(
                f"模板草稿目录缺少可用内容文件：{template_dir}。"
                " 需要 draft_content.json，或 subdraft/draft_content.json。"
            )
        raise SkillError(
            "模板草稿里没有可读取的明文时间线 JSON。"
            f" 当前目录不能直接当模板使用：{template_dir}。"
            f" 详情：{content_error or '未找到可解析内容'}"
        )

    meta: dict[str, Any] = {}
    if draft_meta_path.exists():
        try:
            loaded_meta = json.loads(draft_meta_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError, UnicodeDecodeError):
            loaded_meta = {}
        if isinstance(loaded_meta, dict):
            meta = loaded_meta
    return content, meta


def collect_ids(payload: Any, sink: set[str]) -> None:
    if isinstance(payload, dict):
        value = payload.get("id")
        if isinstance(value, str) and value:
            sink.add(value)
        for child in payload.values():
            collect_ids(child, sink)
        return
    if isinstance(payload, list):
        for child in payload:
            collect_ids(child, sink)


def remap_known_ids(payload: Any, id_map: dict[str, str]) -> Any:
    if isinstance(payload, dict):
        return {key: remap_known_ids(value, id_map) for key, value in payload.items()}
    if isinstance(payload, list):
        return [remap_known_ids(value, id_map) for value in payload]
    if isinstance(payload, str):
        return id_map.get(payload, payload)
    return payload


def shift_track_timeranges(tracks: list[dict[str, Any]], offset_us: int) -> None:
    for track in tracks:
        for segment in track.get("segments", []):
            timerange = segment.get("target_timerange")
            if isinstance(timerange, dict):
                timerange["start"] = int(timerange.get("start", 0)) + offset_us


def ensure_list_field(container: dict[str, Any], key: str) -> list[Any]:
    value = container.get(key)
    if isinstance(value, list):
        return value
    container[key] = []
    return container[key]


def as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def resolve_draft_duration_us(content: dict[str, Any]) -> int:
    raw_duration = int(content.get("duration") or 0)
    if raw_duration > 0:
        return raw_duration

    max_end = 0
    for track in as_list(content.get("tracks")):
        if not isinstance(track, dict):
            continue
        for segment in as_list(track.get("segments")):
            if not isinstance(segment, dict):
                continue
            timerange = segment.get("target_timerange")
            if not isinstance(timerange, dict):
                continue
            start = int(timerange.get("start") or 0)
            duration = int(timerange.get("duration") or 0)
            max_end = max(max_end, start + duration)
    return max_end


def resolve_primary_timeline_id(draft_dir: Path) -> tuple[str, str]:
    timeline_root = draft_dir / "Timelines"
    project_path = timeline_root / "project.json"
    layout_path = draft_dir / "timeline_layout.json"
    project_payload = read_json_object(project_path)
    layout_payload = read_json_object(layout_path)

    candidate_ids: list[str] = []
    for value in (
        project_payload.get("main_timeline_id"),
        layout_payload.get("activeTimeline"),
    ):
        if isinstance(value, str) and value.strip():
            candidate_ids.append(value.strip())

    timelines = project_payload.get("timelines")
    if isinstance(timelines, list):
        for item in timelines:
            if not isinstance(item, dict):
                continue
            value = item.get("id")
            if isinstance(value, str) and value.strip():
                candidate_ids.append(value.strip())

    for timeline_id in candidate_ids:
        timeline_dir = timeline_root / timeline_id
        if timeline_dir.exists():
            return timeline_id, timeline_id

    if candidate_ids:
        return candidate_ids[0], candidate_ids[0]
    generated_id = uuid.uuid4().hex
    return generated_id, generated_id


def sync_modern_timeline_files(draft_dir: Path, draft_name: str, draft_content: dict[str, Any]) -> None:
    timeline_root = draft_dir / "Timelines"
    project_path = timeline_root / "project.json"
    layout_path = draft_dir / "timeline_layout.json"
    timeline_id, timeline_name = resolve_primary_timeline_id(draft_dir)

    timeline_dir = timeline_root / timeline_id
    timeline_dir.mkdir(parents=True, exist_ok=True)
    write_json_object(timeline_dir / "draft_content.json", draft_content)

    project_payload = read_json_object(project_path)
    project_timelines = project_payload.get("timelines")
    if not isinstance(project_timelines, list):
        project_timelines = []

    timeline_entry = None
    for item in project_timelines:
        if isinstance(item, dict) and item.get("id") == timeline_id:
            timeline_entry = item
            break
    if timeline_entry is None:
        timeline_entry = {}
        project_timelines.insert(0, timeline_entry)

    timeline_entry["id"] = timeline_id
    timeline_entry["is_marked_delete"] = False
    timeline_entry["name"] = normalize_text(timeline_entry.get("name") or draft_name or timeline_name or timeline_id)
    timeline_entry["create_time"] = int(timeline_entry.get("create_time") or 0)
    timeline_entry["update_time"] = int(timeline_entry.get("update_time") or 0)

    project_payload["main_timeline_id"] = timeline_id
    project_payload["timelines"] = project_timelines
    write_json_object(project_path, project_payload)

    layout_payload = read_json_object(layout_path)
    layout_payload["activeTimeline"] = timeline_id
    dock_items = layout_payload.get("dockItems")
    if not isinstance(dock_items, list) or not dock_items:
        dock_items = [{"dockIndex": 0, "ratio": 1, "timelineIds": [], "timelineNames": []}]
        layout_payload["dockItems"] = dock_items
    primary_dock = dock_items[0]
    if not isinstance(primary_dock, dict):
        primary_dock = {"dockIndex": 0, "ratio": 1, "timelineIds": [], "timelineNames": []}
        dock_items[0] = primary_dock
    primary_dock["timelineIds"] = [timeline_id]
    primary_dock["timelineNames"] = [timeline_entry["name"]]
    write_json_object(layout_path, layout_payload)


def ensure_output_draft_dir(template_dir: Path, output_dir: Path, allow_replace: bool) -> None:
    if template_dir.resolve() == output_dir.resolve():
        raise SkillError("输出草稿目录不能和模板草稿目录相同，避免污染模板源。")
    if output_dir.exists() and not allow_replace:
        raise SkillError(f"目标草稿已存在，请换一个草稿名或启用覆盖：{output_dir}")
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(template_dir, output_dir, dirs_exist_ok=True)


def create_shell_draft(
    *,
    draft_root: Path,
    draft_name: str,
    canvas_width: int,
    canvas_height: int,
    fps: int,
    allow_replace: bool,
) -> Path:
    draft_folder = draft.DraftFolder(str(draft_root))
    script = draft_folder.create_draft(
        draft_name,
        canvas_width,
        canvas_height,
        fps=fps,
        allow_replace=allow_replace,
    )
    script.save()
    return draft_root / draft_name


def is_openable_draft_dir(draft_dir: Path) -> bool:
    if not draft_dir.exists() or not draft_dir.is_dir():
        return False
    for candidate in (
        draft_dir / "draft_content.json",
        draft_dir / "template-2.tmp",
        draft_dir / "template.tmp",
    ):
        if candidate.exists() and candidate.stat().st_size > 0:
            return True
    timeline_root = draft_dir / "Timelines"
    return timeline_root.exists() and any(path.stat().st_size > 0 for path in timeline_root.rglob("draft_content.json"))


def replace_draft_dir_atomically(staging_dir: Path, final_dir: Path, allow_replace: bool) -> None:
    if not is_openable_draft_dir(staging_dir):
        raise SkillError(f"生成结果缺少草稿内容文件，已停止替换正式草稿：{staging_dir}")
    if final_dir.exists():
        if not allow_replace:
            raise SkillError(f"目标草稿已存在，请换一个草稿名或启用覆盖：{final_dir}")
        backup_dir = final_dir.with_name(f"{final_dir.name}.__replace_backup__")
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        final_dir.rename(backup_dir)
        try:
            staging_dir.rename(final_dir)
            shutil.rmtree(backup_dir, ignore_errors=True)
        except Exception:
            if final_dir.exists():
                shutil.rmtree(final_dir, ignore_errors=True)
            if backup_dir.exists():
                backup_dir.rename(final_dir)
            raise
        return
    staging_dir.rename(final_dir)


def copy_template_assets_into_shell(template_dir: Path, output_dir: Path) -> None:
    excluded_names = {
        ".backup",
        "draft_meta_info.json",
        "draft_content.json",
        "draft_content.json.bak",
        "template-2.tmp",
        "timeline_layout.json",
        "Timelines",
        "draft_biz_config.json",
    }
    for child in template_dir.iterdir():
        if child.name in excluded_names:
            continue
        target = output_dir / child.name
        if child.is_dir():
            shutil.copytree(child, target, dirs_exist_ok=True)
        elif child.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(child, target)


def write_draft_content_payload(base_file: Path, payload: dict[str, Any]) -> None:
    write_json_object(base_file, payload)
    for sibling_name in ("draft_content.json.bak", "template-2.tmp", "template.tmp"):
        sibling_path = base_file.with_name(sibling_name)
        if sibling_path.exists():
            write_json_object(sibling_path, payload)


def write_into_active_timeline_if_present(draft_dir: Path, payload: dict[str, Any]) -> None:
    layout_path = draft_dir / "timeline_layout.json"
    project_path = draft_dir / "Timelines" / "project.json"
    layout_payload = read_json_object(layout_path)
    project_payload = read_json_object(project_path)
    candidate_ids: list[str] = []
    active_id = normalize_text(layout_payload.get("activeTimeline"))
    if active_id:
        candidate_ids.append(active_id)
    main_id = normalize_text(project_payload.get("main_timeline_id"))
    if main_id and main_id not in candidate_ids:
        candidate_ids.append(main_id)
    for timeline in as_list(project_payload.get("timelines")):
        if isinstance(timeline, dict):
            timeline_id = normalize_text(timeline.get("id"))
            if timeline_id and timeline_id not in candidate_ids:
                candidate_ids.append(timeline_id)

    for timeline_id in candidate_ids:
        timeline_file = draft_dir / "Timelines" / timeline_id / "draft_content.json"
        if timeline_file.exists():
            write_draft_content_payload(timeline_file, payload)
            return


def merge_template_with_generated_tail(
    template_dir: Path,
    generated_tail_dir: Path,
    output_dir: Path,
    output_name: str,
    allow_replace: bool,
    *,
    draft_root: Path,
    canvas_width: int,
    canvas_height: int,
    fps: int,
) -> tuple[float, dict[str, int]]:
    template_content, _template_meta = load_template_draft(template_dir)
    tail_content, _tail_meta = load_template_draft(generated_tail_dir)
    output_dir = create_shell_draft(
        draft_root=draft_root,
        draft_name=output_name,
        canvas_width=canvas_width,
        canvas_height=canvas_height,
        fps=fps,
        allow_replace=allow_replace,
    )
    shell_meta = read_json_object(output_dir / "draft_meta_info.json")
    copy_template_assets_into_shell(template_dir, output_dir)

    merged_content = copy.deepcopy(template_content)
    template_duration_us = resolve_draft_duration_us(merged_content)
    tail_duration_us = resolve_draft_duration_us(tail_content)

    tail_ids: set[str] = set()
    collect_ids(tail_content, tail_ids)
    id_map = {old_id: uuid.uuid4().hex for old_id in tail_ids}
    remapped_tail = remap_known_ids(copy.deepcopy(tail_content), id_map)
    shift_track_timeranges(remapped_tail.get("tracks", []), template_duration_us)

    merged_content["id"] = uuid.uuid4().hex
    merged_content["name"] = output_name
    merged_content["duration"] = template_duration_us + tail_duration_us
    merged_content["update_time"] = 0
    merged_content["create_time"] = 0

    merged_materials = merged_content.setdefault("materials", {})
    for key, tail_items in (remapped_tail.get("materials") or {}).items():
        if isinstance(tail_items, list):
            ensure_list_field(merged_materials, key).extend(tail_items)

    merged_keyframes = merged_content.setdefault("keyframes", {})
    for key, tail_items in (remapped_tail.get("keyframes") or {}).items():
        if isinstance(tail_items, list):
            ensure_list_field(merged_keyframes, key).extend(tail_items)

    ensure_list_field(merged_content, "relationships").extend(as_list(remapped_tail.get("relationships")))
    ensure_list_field(merged_content, "keyframe_graph_list").extend(as_list(remapped_tail.get("keyframe_graph_list")))
    ensure_list_field(merged_content, "time_marks").extend(as_list(remapped_tail.get("time_marks")))
    ensure_list_field(merged_content, "tracks").extend(as_list(remapped_tail.get("tracks")))

    write_draft_content_payload(output_dir / "draft_content.json", merged_content)
    write_into_active_timeline_if_present(output_dir, merged_content)
    return merged_content["duration"] / 1_000_000, {
        "template_duration_us": template_duration_us,
        "tail_duration_us": tail_duration_us,
        "appended_tracks": len(remapped_tail.get("tracks", [])),
    }


def build_generated_draft(
    *,
    draft_root: Path,
    draft_name: str,
    canvas_width: int,
    canvas_height: int,
    fps: int,
    background_image: Path,
    items: list[ClipItem],
    intro_item: ClipItem | None,
    manifest_path: Path | None,
    manifest_mode: str,
    match_summary: dict[str, Any],
    subtitle_model: str,
    subtitle_language: str,
    subtitle_engine: str,
    skip_subtitles: bool,
    subtitle_vad_filter: bool,
    allow_replace: bool,
) -> dict[str, Any]:
    timeline_items = ([intro_item] if intro_item is not None else []) + items
    voice_gap_count = max(len(timeline_items) - 1, 0)
    total_voice_gap_sec = voice_gap_count * VOICE_CLIP_GAP_SEC
    total_duration_sec = sum(item.duration_sec for item in timeline_items) + total_voice_gap_sec
    draft_folder = draft.DraftFolder(str(draft_root))
    script = draft_folder.create_draft(
        draft_name,
        canvas_width,
        canvas_height,
        fps=fps,
        allow_replace=allow_replace,
    )
    script.add_track(draft.TrackType.video, "background")
    script.add_track(draft.TrackType.video, "media", relative_index=1)
    script.add_track(draft.TrackType.video, "display_video", relative_index=2)
    script.add_track(draft.TrackType.audio, "voice")

    subtitle_style = draft.TextStyle(size=5, align=1, auto_wrapping=True)
    subtitle_clip = draft.ClipSettings(transform_y=-0.8)
    subtitle_segments: list[SubtitleSegment] = []
    missing_subtitle_texts: list[str] = []

    background_segment = draft.VideoSegment(
        str(background_image),
        trange("0s", sec_text(total_duration_sec)),
    )
    script.add_segment(background_segment, "background")
    price_title_image_dir = draft_root / PRICE_TITLE_CACHE_DIR_NAME / safe_path_component(draft_name)

    audio_cursor = 0.0
    visual_cursor = 0.0
    media_segments: list[tuple[int, Any]] = []
    display_video_segments: list[Any] = []
    audio_segments: list[Any] = []
    price_transition_title_segments: list[Any] = []
    for item_index, item in enumerate(timeline_items):
        if not skip_subtitles and item.source_type != "intro_video":
            if item.subtitle_text:
                subtitle_segments.extend(
                    build_subtitle_segments(
                        item.audio_path,
                        item.subtitle_text,
                        audio_cursor,
                        subtitle_model,
                        subtitle_language,
                        subtitle_engine,
                        vad_filter=subtitle_vad_filter,
                    )
                )
            else:
                missing_subtitle_texts.append(item.audio_path.name)

        if item.media_path is not None:
            media_duration_sec = item.duration_sec
            media_segments.append(
                (
                    item_index,
                    draft.VideoSegment(
                        str(item.media_path),
                        trange(sec_text(visual_cursor), sec_text(media_duration_sec)),
                        clip_settings=build_media_clip_settings(item.media_path, canvas_width, canvas_height),
                    ),
                )
            )
        if item.display_video_path is not None and item.display_video_slot is not None:
            display_duration = max(min(probe_media_duration(item.display_video_path), item.duration_sec) - 0.02, 0.1)
            display_video_segments.append(
                draft.VideoSegment(
                    str(item.display_video_path),
                    trange(sec_text(visual_cursor), sec_text(display_duration)),
                    source_timerange=trange("0s", sec_text(display_duration)),
                    volume=0.0,
                    clip_settings=build_display_video_clip_settings(
                        item.display_video_path,
                        item.display_video_slot,
                        canvas_width,
                        canvas_height,
                    ),
                )
            )
        if item.source_type != "intro_video":
            if item.price_transition_title:
                price_transition_title_segments.append(
                    build_price_transition_title_segment(
                        item.price_transition_title,
                        audio_cursor,
                        item.duration_sec,
                        price_title_image_dir,
                        canvas_width,
                        canvas_height,
                    )
                )
            audio_segments.append(
                draft.AudioSegment(
                    str(item.audio_path),
                    trange(sec_text(audio_cursor), sec_text(item.duration_sec)),
                )
            )
        visual_cursor += item.duration_sec
        audio_cursor += item.duration_sec
        if item_index < len(timeline_items) - 1:
            audio_cursor += VOICE_CLIP_GAP_SEC

    transition_type = getattr(draft.TransitionType, "翻页", None)
    if transition_type is not None:
        for index in range(len(media_segments) - 1):
            current_item_index, media_segment = media_segments[index]
            next_item_index, _next_media_segment = media_segments[index + 1]
            if next_item_index != current_item_index + 1:
                continue
            if timeline_items[current_item_index].source_type == "intro_video":
                continue
            media_segment.add_transition(transition_type)

    for _item_index, media_segment in media_segments:
        script.add_segment(media_segment, "media")
    for display_video_segment in display_video_segments:
        script.add_segment(display_video_segment, "display_video")
    for audio_segment in audio_segments:
        script.add_segment(audio_segment, "voice")

    if price_transition_title_segments:
        script.add_track(draft.TrackType.video, "price_transition_title", relative_index=3)
        for title_segment in price_transition_title_segments:
            script.add_segment(title_segment, "price_transition_title")

    if subtitle_segments:
        script.add_track(draft.TrackType.text, "subtitle", relative_index=999)
        for subtitle in subtitle_segments:
            script.add_segment(
                draft.TextSegment(
                    subtitle.text,
                    trange(sec_text(subtitle.start_sec), sec_text(subtitle.duration_sec)),
                    style=subtitle_style,
                    clip_settings=subtitle_clip,
                ),
                "subtitle",
            )

    script.save()
    draft_dir = draft_root / draft_name
    return {
        "draft_root": str(draft_root),
        "draft_name": draft_name,
        "draft_dir": str(draft_dir),
        "manifest_path": str(manifest_path) if manifest_path else "",
        "match_mode": manifest_mode,
        "subtitle_engine": subtitle_engine,
        "total_items": len(timeline_items),
        "product_items": len(items),
        "total_duration_sec": round(audio_cursor, 3),
        "voice_clip_gap_sec": VOICE_CLIP_GAP_SEC,
        "total_voice_gap_sec": round(total_voice_gap_sec, 3),
        "background_image": str(background_image),
        "has_intro_video": intro_item is not None,
        "intro_video_path": str(intro_item.media_path) if intro_item is not None else "",
        "intro_duration_sec": round(intro_item.duration_sec, 3) if intro_item is not None else 0.0,
        "subtitle_segments": len(subtitle_segments),
        "display_video_segments": len(display_video_segments),
        "price_transition_title_segments": len(price_transition_title_segments),
        "missing_subtitle_texts": missing_subtitle_texts,
        "image_fallback": match_summary.get("image_fallback", {}),
        "skipped_entries": match_summary.get("skipped_entries", []),
        "skipped_display_videos": match_summary.get("skipped_display_videos", []),
        "unmatched_audio": match_summary.get("unmatched_audio", []),
        "unused_images": match_summary.get("unused_images", []),
    }


def main() -> None:
    args = parse_args()
    try:
        ensure_runtime_dependencies()
        if args.intro_video and args.template_draft:
            raise SkillError("不能同时传入前置引言视频和模板草稿目录，请二选一。")
        draft_root = Path(args.draft_root).resolve()
        draft_root.mkdir(parents=True, exist_ok=True)
        background_image = Path(args.background_image).resolve()
        if not background_image.exists():
            raise FileNotFoundError(f"背景图不存在：{background_image}")
        template_draft_dir = Path(args.template_draft).resolve() if args.template_draft else None
        template_content: dict[str, Any] | None = None
        if template_draft_dir is not None:
            template_content, _ = load_template_draft(template_draft_dir)

        if args.manifest:
            manifest_path = Path(args.manifest).resolve()
            if not manifest_path.exists():
                raise FileNotFoundError(f"Manifest 不存在：{manifest_path}")
            image_index_path = (
                Path(args.image_index_path).resolve()
                if args.image_index_path
                else DEFAULT_IMAGE_INDEX_PATH.resolve()
            )
            items, match_summary = build_items_from_manifest(
                manifest_path,
                image_category=normalize_text(args.image_category),
                image_user=normalize_text(args.image_user),
                image_set=normalize_text(args.image_set),
                image_index_path=image_index_path,
            )
            manifest_mode = match_summary["match_mode"]
        else:
            if not args.image_dir or not args.audio_dir:
                raise SkillError("如果不传 manifest，就必须同时传 `--image-dir` 和 `--audio-dir`。")
            items, match_summary = build_items_from_directories(Path(args.image_dir).resolve(), Path(args.audio_dir).resolve())
            manifest_path = None
            manifest_mode = match_summary["match_mode"]

        draft_name = args.draft_name
        if draft_name == DEFAULT_DRAFT_NAME and manifest_path is not None:
            draft_name = build_default_draft_name(manifest_path)
        final_draft_name = draft_name
        final_draft_dir = draft_root / final_draft_name
        staging_draft_name = f"{final_draft_name}.__building__{uuid.uuid4().hex[:8]}"
        intro_audio_dir = draft_root / INTRO_AUDIO_CACHE_DIR_NAME / safe_path_component(draft_name)
        intro_item = build_intro_clip_item(Path(args.intro_video).resolve(), intro_audio_dir) if args.intro_video else None

        canvas_width = int(template_content.get("canvas_config", {}).get("width", args.width)) if template_content else args.width
        canvas_height = int(template_content.get("canvas_config", {}).get("height", args.height)) if template_content else args.height
        fps = int(template_content.get("fps", args.fps)) if template_content else args.fps

        if template_draft_dir is None:
            summary = build_generated_draft(
                draft_root=draft_root,
                draft_name=staging_draft_name,
                canvas_width=canvas_width,
                canvas_height=canvas_height,
                fps=fps,
                background_image=background_image,
                items=items,
                intro_item=intro_item,
                manifest_path=manifest_path,
                manifest_mode=manifest_mode,
                match_summary=match_summary,
                subtitle_model=args.subtitle_model,
                subtitle_language=args.subtitle_language,
                subtitle_engine=args.subtitle_engine,
                skip_subtitles=args.skip_subtitles,
                subtitle_vad_filter=not args.subtitle_no_vad,
                allow_replace=False,
            )
            staging_draft_dir = Path(summary["draft_dir"])
            replace_draft_dir_atomically(staging_draft_dir, final_draft_dir, args.allow_replace)
            summary["draft_name"] = final_draft_name
            summary["draft_dir"] = str(final_draft_dir)
            patch_draft_content_media_metadata(final_draft_dir)
            update_draft_meta(final_draft_dir, final_draft_name, float(summary["total_duration_sec"]))
        else:
            with tempfile.TemporaryDirectory(prefix="jy-tail-") as temp_root:
                temp_root_path = Path(temp_root).resolve()
                tail_name = f"{staging_draft_name}__tail"
                tail_summary = build_generated_draft(
                    draft_root=temp_root_path,
                    draft_name=tail_name,
                    canvas_width=canvas_width,
                    canvas_height=canvas_height,
                    fps=fps,
                    background_image=background_image,
                    items=items,
                    intro_item=None,
                    manifest_path=manifest_path,
                    manifest_mode=manifest_mode,
                    match_summary=match_summary,
                    subtitle_model=args.subtitle_model,
                    subtitle_language=args.subtitle_language,
                    subtitle_engine=args.subtitle_engine,
                    skip_subtitles=args.skip_subtitles,
                    subtitle_vad_filter=not args.subtitle_no_vad,
                    allow_replace=True,
                )
                staging_final_dir = draft_root / staging_draft_name
                final_duration_sec, merge_summary = merge_template_with_generated_tail(
                    template_draft_dir,
                    Path(tail_summary["draft_dir"]),
                    staging_final_dir,
                    staging_draft_name,
                    False,
                    draft_root=draft_root,
                    canvas_width=canvas_width,
                    canvas_height=canvas_height,
                    fps=fps,
                )
                replace_draft_dir_atomically(staging_final_dir, final_draft_dir, args.allow_replace)
                patch_draft_content_media_metadata(final_draft_dir)
                update_draft_meta(final_draft_dir, final_draft_name, final_duration_sec)
                summary = {
                    **tail_summary,
                    "draft_root": str(draft_root),
                    "draft_name": final_draft_name,
                    "draft_dir": str(final_draft_dir),
                    "template_draft_dir": str(template_draft_dir),
                    "assembly_mode": "template_append",
                    "total_duration_sec": round(final_duration_sec, 3),
                    "merge_summary": merge_summary,
                }

        summary["status"] = "success"
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    except Exception as exc:
        print(json.dumps({"status": "failed", "error": str(exc)}, ensure_ascii=False, indent=2))
        sys.exit(1)


if __name__ == "__main__":
    main()
